sonar.projectKey=Winksluizeman_BuffelSimulatorFrontend
sonar.organization=Winksluizeman
sonar.projectName=BuffelSimulatorFrontend
sonar.sources=src
sonar.tests=cypress
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts
sonar.typescript.tsconfigPath=tsconfig.json
